/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.coral.portugolcoral.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage
 * @generated
 */
public class PortugolcoralSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static PortugolcoralPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PortugolcoralSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = PortugolcoralPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case PortugolcoralPackage.PORTUGOLCORAL:
      {
        Portugolcoral portugolcoral = (Portugolcoral)theEObject;
        T result = casePortugolcoral(portugolcoral);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.ACOES:
      {
        Acoes acoes = (Acoes)theEObject;
        T result = caseAcoes(acoes);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.DECLARAR_VARIAVEIS:
      {
        DeclararVariaveis declararVariaveis = (DeclararVariaveis)theEObject;
        T result = caseDeclararVariaveis(declararVariaveis);
        if (result == null) result = caseAcoes(declararVariaveis);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.DECLARAR_VARIAVEIS_TIPO:
      {
        DeclararVariaveisTipo declararVariaveisTipo = (DeclararVariaveisTipo)theEObject;
        T result = caseDeclararVariaveisTipo(declararVariaveisTipo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.ATRIBUIR:
      {
        Atribuir atribuir = (Atribuir)theEObject;
        T result = caseAtribuir(atribuir);
        if (result == null) result = caseAcoes(atribuir);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.EXPRESSAO:
      {
        Expressao expressao = (Expressao)theEObject;
        T result = caseExpressao(expressao);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.NAO:
      {
        Nao nao = (Nao)theEObject;
        T result = caseNao(nao);
        if (result == null) result = caseExpressao(nao);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.SINAL:
      {
        Sinal sinal = (Sinal)theEObject;
        T result = caseSinal(sinal);
        if (result == null) result = caseExpressao(sinal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.ELEMENTO_PARENTESES:
      {
        ElementoParenteses elementoParenteses = (ElementoParenteses)theEObject;
        T result = caseElementoParenteses(elementoParenteses);
        if (result == null) result = caseExpressao(elementoParenteses);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.PARENTESES:
      {
        Parenteses parenteses = (Parenteses)theEObject;
        T result = caseParenteses(parenteses);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.MATRIZ:
      {
        Matriz matriz = (Matriz)theEObject;
        T result = caseMatriz(matriz);
        if (result == null) result = caseExpressao(matriz);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.POSICAO_MATRIZ:
      {
        PosicaoMatriz posicaoMatriz = (PosicaoMatriz)theEObject;
        T result = casePosicaoMatriz(posicaoMatriz);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.OU:
      {
        Ou ou = (Ou)theEObject;
        T result = caseOu(ou);
        if (result == null) result = caseExpressao(ou);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.E:
      {
        E e = (E)theEObject;
        T result = caseE(e);
        if (result == null) result = caseExpressao(e);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.XOU:
      {
        Xou xou = (Xou)theEObject;
        T result = caseXou(xou);
        if (result == null) result = caseExpressao(xou);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.COMPARACAO:
      {
        Comparacao comparacao = (Comparacao)theEObject;
        T result = caseComparacao(comparacao);
        if (result == null) result = caseExpressao(comparacao);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.ADICAO_OU_SUBTRACAO:
      {
        AdicaoOuSubtracao adicaoOuSubtracao = (AdicaoOuSubtracao)theEObject;
        T result = caseAdicaoOuSubtracao(adicaoOuSubtracao);
        if (result == null) result = caseExpressao(adicaoOuSubtracao);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO:
      {
        MultiplicacaoOuDivisao multiplicacaoOuDivisao = (MultiplicacaoOuDivisao)theEObject;
        T result = caseMultiplicacaoOuDivisao(multiplicacaoOuDivisao);
        if (result == null) result = caseExpressao(multiplicacaoOuDivisao);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.EXPONENCIACAO:
      {
        Exponenciacao exponenciacao = (Exponenciacao)theEObject;
        T result = caseExponenciacao(exponenciacao);
        if (result == null) result = caseExpressao(exponenciacao);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.CONSTANTE_INTEIRA:
      {
        ConstanteInteira constanteInteira = (ConstanteInteira)theEObject;
        T result = caseConstanteInteira(constanteInteira);
        if (result == null) result = caseExpressao(constanteInteira);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.CONSTANTE_REAL:
      {
        ConstanteReal constanteReal = (ConstanteReal)theEObject;
        T result = caseConstanteReal(constanteReal);
        if (result == null) result = caseExpressao(constanteReal);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.CONSTANTE_STRING:
      {
        ConstanteString constanteString = (ConstanteString)theEObject;
        T result = caseConstanteString(constanteString);
        if (result == null) result = caseExpressao(constanteString);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case PortugolcoralPackage.REFERENCIA_VARIAVEL:
      {
        ReferenciaVariavel referenciaVariavel = (ReferenciaVariavel)theEObject;
        T result = caseReferenciaVariavel(referenciaVariavel);
        if (result == null) result = caseExpressao(referenciaVariavel);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Portugolcoral</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Portugolcoral</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePortugolcoral(Portugolcoral object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Acoes</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Acoes</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAcoes(Acoes object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Declarar Variaveis</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Declarar Variaveis</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDeclararVariaveis(DeclararVariaveis object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Declarar Variaveis Tipo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Declarar Variaveis Tipo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDeclararVariaveisTipo(DeclararVariaveisTipo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Atribuir</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Atribuir</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAtribuir(Atribuir object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expressao</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expressao</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressao(Expressao object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Nao</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Nao</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNao(Nao object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Sinal</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Sinal</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSinal(Sinal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Elemento Parenteses</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Elemento Parenteses</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseElementoParenteses(ElementoParenteses object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Parenteses</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Parenteses</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseParenteses(Parenteses object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Matriz</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Matriz</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMatriz(Matriz object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Posicao Matriz</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Posicao Matriz</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePosicaoMatriz(PosicaoMatriz object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Ou</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Ou</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseOu(Ou object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>E</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>E</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseE(E object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Xou</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Xou</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseXou(Xou object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Comparacao</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Comparacao</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseComparacao(Comparacao object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Adicao Ou Subtracao</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Adicao Ou Subtracao</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAdicaoOuSubtracao(AdicaoOuSubtracao object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Multiplicacao Ou Divisao</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Multiplicacao Ou Divisao</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMultiplicacaoOuDivisao(MultiplicacaoOuDivisao object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Exponenciacao</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Exponenciacao</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExponenciacao(Exponenciacao object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Constante Inteira</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Constante Inteira</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConstanteInteira(ConstanteInteira object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Constante Real</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Constante Real</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConstanteReal(ConstanteReal object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Constante String</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Constante String</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConstanteString(ConstanteString object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Referencia Variavel</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Referencia Variavel</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseReferenciaVariavel(ReferenciaVariavel object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //PortugolcoralSwitch
