/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.ide;

import org.xtext.coral.ide.AbstractPortugolCoralIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PortugolCoralIdeModule extends AbstractPortugolCoralIdeModule {
}
