/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.coral.ui.AbstractPortugolCoralUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PortugolCoralUiModule extends AbstractPortugolCoralUiModule {
  public PortugolCoralUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
