/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral;

import org.xtext.coral.PortugolCoralStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PortugolCoralStandaloneSetup extends PortugolCoralStandaloneSetupGenerated {
  public static void doSetup() {
    new PortugolCoralStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
