/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral;

import org.xtext.coral.AbstractPortugolCoralRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PortugolCoralRuntimeModule extends AbstractPortugolCoralRuntimeModule {
}
