/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Acoes</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getAcoes()
 * @model
 * @generated
 */
public interface Acoes extends EObject
{
} // Acoes
