/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Adicao Ou Subtracao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.AdicaoOuSubtracao#getOperacao <em>Operacao</em>}</li>
 *   <li>{@link org.xtext.coral.portugolcoral.AdicaoOuSubtracao#getDireita <em>Direita</em>}</li>
 * </ul>
 *
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getAdicaoOuSubtracao()
 * @model
 * @generated
 */
public interface AdicaoOuSubtracao extends Expressao
{
  /**
   * Returns the value of the '<em><b>Operacao</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operacao</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operacao</em>' attribute.
   * @see #setOperacao(String)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getAdicaoOuSubtracao_Operacao()
   * @model
   * @generated
   */
  String getOperacao();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.AdicaoOuSubtracao#getOperacao <em>Operacao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operacao</em>' attribute.
   * @see #getOperacao()
   * @generated
   */
  void setOperacao(String value);

  /**
   * Returns the value of the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direita</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direita</em>' containment reference.
   * @see #setDireita(Expressao)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getAdicaoOuSubtracao_Direita()
   * @model containment="true"
   * @generated
   */
  Expressao getDireita();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.AdicaoOuSubtracao#getDireita <em>Direita</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direita</em>' containment reference.
   * @see #getDireita()
   * @generated
   */
  void setDireita(Expressao value);

} // AdicaoOuSubtracao
