/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atribuir</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.Atribuir#getVariavel <em>Variavel</em>}</li>
 *   <li>{@link org.xtext.coral.portugolcoral.Atribuir#getValor <em>Valor</em>}</li>
 * </ul>
 *
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getAtribuir()
 * @model
 * @generated
 */
public interface Atribuir extends Acoes
{
  /**
   * Returns the value of the '<em><b>Variavel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variavel</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variavel</em>' attribute.
   * @see #setVariavel(String)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getAtribuir_Variavel()
   * @model
   * @generated
   */
  String getVariavel();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.Atribuir#getVariavel <em>Variavel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variavel</em>' attribute.
   * @see #getVariavel()
   * @generated
   */
  void setVariavel(String value);

  /**
   * Returns the value of the '<em><b>Valor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Valor</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' containment reference.
   * @see #setValor(Expressao)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getAtribuir_Valor()
   * @model containment="true"
   * @generated
   */
  Expressao getValor();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.Atribuir#getValor <em>Valor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' containment reference.
   * @see #getValor()
   * @generated
   */
  void setValor(Expressao value);

} // Atribuir
