/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparacao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.Comparacao#getComparacao <em>Comparacao</em>}</li>
 *   <li>{@link org.xtext.coral.portugolcoral.Comparacao#getDireita <em>Direita</em>}</li>
 * </ul>
 *
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getComparacao()
 * @model
 * @generated
 */
public interface Comparacao extends Expressao
{
  /**
   * Returns the value of the '<em><b>Comparacao</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comparacao</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparacao</em>' attribute.
   * @see #setComparacao(String)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getComparacao_Comparacao()
   * @model
   * @generated
   */
  String getComparacao();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.Comparacao#getComparacao <em>Comparacao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparacao</em>' attribute.
   * @see #getComparacao()
   * @generated
   */
  void setComparacao(String value);

  /**
   * Returns the value of the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direita</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direita</em>' containment reference.
   * @see #setDireita(Expressao)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getComparacao_Direita()
   * @model containment="true"
   * @generated
   */
  Expressao getDireita();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.Comparacao#getDireita <em>Direita</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direita</em>' containment reference.
   * @see #getDireita()
   * @generated
   */
  void setDireita(Expressao value);

} // Comparacao
