/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constante String</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.ConstanteString#getValor <em>Valor</em>}</li>
 * </ul>
 *
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getConstanteString()
 * @model
 * @generated
 */
public interface ConstanteString extends Expressao
{
  /**
   * Returns the value of the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Valor</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valor</em>' attribute.
   * @see #setValor(String)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getConstanteString_Valor()
   * @model
   * @generated
   */
  String getValor();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.ConstanteString#getValor <em>Valor</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valor</em>' attribute.
   * @see #getValor()
   * @generated
   */
  void setValor(String value);

} // ConstanteString
