/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarar Variaveis</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.DeclararVariaveis#getElementos <em>Elementos</em>}</li>
 * </ul>
 *
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getDeclararVariaveis()
 * @model
 * @generated
 */
public interface DeclararVariaveis extends Acoes
{
  /**
   * Returns the value of the '<em><b>Elementos</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.coral.portugolcoral.DeclararVariaveisTipo}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elementos</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elementos</em>' containment reference list.
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getDeclararVariaveis_Elementos()
   * @model containment="true"
   * @generated
   */
  EList<DeclararVariaveisTipo> getElementos();

} // DeclararVariaveis
