/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declarar Variaveis Tipo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.DeclararVariaveisTipo#getElementos <em>Elementos</em>}</li>
 *   <li>{@link org.xtext.coral.portugolcoral.DeclararVariaveisTipo#getTipo <em>Tipo</em>}</li>
 * </ul>
 *
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getDeclararVariaveisTipo()
 * @model
 * @generated
 */
public interface DeclararVariaveisTipo extends EObject
{
  /**
   * Returns the value of the '<em><b>Elementos</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elementos</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elementos</em>' attribute list.
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getDeclararVariaveisTipo_Elementos()
   * @model unique="false"
   * @generated
   */
  EList<String> getElementos();

  /**
   * Returns the value of the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tipo</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tipo</em>' attribute.
   * @see #setTipo(String)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getDeclararVariaveisTipo_Tipo()
   * @model
   * @generated
   */
  String getTipo();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.DeclararVariaveisTipo#getTipo <em>Tipo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tipo</em>' attribute.
   * @see #getTipo()
   * @generated
   */
  void setTipo(String value);

} // DeclararVariaveisTipo
