/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expressao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.Expressao#getEsquerda <em>Esquerda</em>}</li>
 * </ul>
 *
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getExpressao()
 * @model
 * @generated
 */
public interface Expressao extends EObject
{
  /**
   * Returns the value of the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Esquerda</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Esquerda</em>' containment reference.
   * @see #setEsquerda(Expressao)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getExpressao_Esquerda()
   * @model containment="true"
   * @generated
   */
  Expressao getEsquerda();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.Expressao#getEsquerda <em>Esquerda</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Esquerda</em>' containment reference.
   * @see #getEsquerda()
   * @generated
   */
  void setEsquerda(Expressao value);

} // Expressao
