/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.Nao#getNaos <em>Naos</em>}</li>
 *   <li>{@link org.xtext.coral.portugolcoral.Nao#getDireita <em>Direita</em>}</li>
 * </ul>
 *
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getNao()
 * @model
 * @generated
 */
public interface Nao extends Expressao
{
  /**
   * Returns the value of the '<em><b>Naos</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Naos</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Naos</em>' attribute list.
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getNao_Naos()
   * @model unique="false"
   * @generated
   */
  EList<String> getNaos();

  /**
   * Returns the value of the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direita</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direita</em>' containment reference.
   * @see #setDireita(Expressao)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getNao_Direita()
   * @model containment="true"
   * @generated
   */
  Expressao getDireita();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.Nao#getDireita <em>Direita</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direita</em>' containment reference.
   * @see #getDireita()
   * @generated
   */
  void setDireita(Expressao value);

} // Nao
