/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage
 * @generated
 */
public interface PortugolcoralFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PortugolcoralFactory eINSTANCE = org.xtext.coral.portugolcoral.impl.PortugolcoralFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Portugolcoral</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Portugolcoral</em>'.
   * @generated
   */
  Portugolcoral createPortugolcoral();

  /**
   * Returns a new object of class '<em>Acoes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Acoes</em>'.
   * @generated
   */
  Acoes createAcoes();

  /**
   * Returns a new object of class '<em>Declarar Variaveis</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarar Variaveis</em>'.
   * @generated
   */
  DeclararVariaveis createDeclararVariaveis();

  /**
   * Returns a new object of class '<em>Declarar Variaveis Tipo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Declarar Variaveis Tipo</em>'.
   * @generated
   */
  DeclararVariaveisTipo createDeclararVariaveisTipo();

  /**
   * Returns a new object of class '<em>Atribuir</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atribuir</em>'.
   * @generated
   */
  Atribuir createAtribuir();

  /**
   * Returns a new object of class '<em>Expressao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expressao</em>'.
   * @generated
   */
  Expressao createExpressao();

  /**
   * Returns a new object of class '<em>Nao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Nao</em>'.
   * @generated
   */
  Nao createNao();

  /**
   * Returns a new object of class '<em>Sinal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sinal</em>'.
   * @generated
   */
  Sinal createSinal();

  /**
   * Returns a new object of class '<em>Elemento Parenteses</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Elemento Parenteses</em>'.
   * @generated
   */
  ElementoParenteses createElementoParenteses();

  /**
   * Returns a new object of class '<em>Parenteses</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parenteses</em>'.
   * @generated
   */
  Parenteses createParenteses();

  /**
   * Returns a new object of class '<em>Matriz</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Matriz</em>'.
   * @generated
   */
  Matriz createMatriz();

  /**
   * Returns a new object of class '<em>Posicao Matriz</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Posicao Matriz</em>'.
   * @generated
   */
  PosicaoMatriz createPosicaoMatriz();

  /**
   * Returns a new object of class '<em>Ou</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ou</em>'.
   * @generated
   */
  Ou createOu();

  /**
   * Returns a new object of class '<em>E</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>E</em>'.
   * @generated
   */
  E createE();

  /**
   * Returns a new object of class '<em>Xou</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Xou</em>'.
   * @generated
   */
  Xou createXou();

  /**
   * Returns a new object of class '<em>Comparacao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Comparacao</em>'.
   * @generated
   */
  Comparacao createComparacao();

  /**
   * Returns a new object of class '<em>Adicao Ou Subtracao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Adicao Ou Subtracao</em>'.
   * @generated
   */
  AdicaoOuSubtracao createAdicaoOuSubtracao();

  /**
   * Returns a new object of class '<em>Multiplicacao Ou Divisao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multiplicacao Ou Divisao</em>'.
   * @generated
   */
  MultiplicacaoOuDivisao createMultiplicacaoOuDivisao();

  /**
   * Returns a new object of class '<em>Exponenciacao</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exponenciacao</em>'.
   * @generated
   */
  Exponenciacao createExponenciacao();

  /**
   * Returns a new object of class '<em>Constante Inteira</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constante Inteira</em>'.
   * @generated
   */
  ConstanteInteira createConstanteInteira();

  /**
   * Returns a new object of class '<em>Constante Real</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constante Real</em>'.
   * @generated
   */
  ConstanteReal createConstanteReal();

  /**
   * Returns a new object of class '<em>Constante String</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constante String</em>'.
   * @generated
   */
  ConstanteString createConstanteString();

  /**
   * Returns a new object of class '<em>Referencia Variavel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Referencia Variavel</em>'.
   * @generated
   */
  ReferenciaVariavel createReferenciaVariavel();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  PortugolcoralPackage getPortugolcoralPackage();

} //PortugolcoralFactory
