/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.coral.portugolcoral.PortugolcoralFactory
 * @model kind="package"
 * @generated
 */
public interface PortugolcoralPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "portugolcoral";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/portugolcoral/PortugolCoral";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "portugolcoral";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PortugolcoralPackage eINSTANCE = org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.PortugolcoralImpl <em>Portugolcoral</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getPortugolcoral()
   * @generated
   */
  int PORTUGOLCORAL = 0;

  /**
   * The feature id for the '<em><b>Elementos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTUGOLCORAL__ELEMENTOS = 0;

  /**
   * The number of structural features of the '<em>Portugolcoral</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTUGOLCORAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.AcoesImpl <em>Acoes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.AcoesImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getAcoes()
   * @generated
   */
  int ACOES = 1;

  /**
   * The number of structural features of the '<em>Acoes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACOES_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.DeclararVariaveisImpl <em>Declarar Variaveis</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.DeclararVariaveisImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getDeclararVariaveis()
   * @generated
   */
  int DECLARAR_VARIAVEIS = 2;

  /**
   * The feature id for the '<em><b>Elementos</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARAR_VARIAVEIS__ELEMENTOS = ACOES_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Declarar Variaveis</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARAR_VARIAVEIS_FEATURE_COUNT = ACOES_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.DeclararVariaveisTipoImpl <em>Declarar Variaveis Tipo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.DeclararVariaveisTipoImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getDeclararVariaveisTipo()
   * @generated
   */
  int DECLARAR_VARIAVEIS_TIPO = 3;

  /**
   * The feature id for the '<em><b>Elementos</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARAR_VARIAVEIS_TIPO__ELEMENTOS = 0;

  /**
   * The feature id for the '<em><b>Tipo</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARAR_VARIAVEIS_TIPO__TIPO = 1;

  /**
   * The number of structural features of the '<em>Declarar Variaveis Tipo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARAR_VARIAVEIS_TIPO_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.AtribuirImpl <em>Atribuir</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.AtribuirImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getAtribuir()
   * @generated
   */
  int ATRIBUIR = 4;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUIR__VARIAVEL = ACOES_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Valor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUIR__VALOR = ACOES_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Atribuir</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATRIBUIR_FEATURE_COUNT = ACOES_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.ExpressaoImpl <em>Expressao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.ExpressaoImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getExpressao()
   * @generated
   */
  int EXPRESSAO = 5;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO__ESQUERDA = 0;

  /**
   * The number of structural features of the '<em>Expressao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.NaoImpl <em>Nao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.NaoImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getNao()
   * @generated
   */
  int NAO = 6;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAO__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Naos</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAO__NAOS = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAO__DIREITA = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Nao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAO_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.SinalImpl <em>Sinal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.SinalImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getSinal()
   * @generated
   */
  int SINAL = 7;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINAL__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Sinais</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINAL__SINAIS = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINAL__DIREITA = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Sinal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINAL_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.ElementoParentesesImpl <em>Elemento Parenteses</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.ElementoParentesesImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getElementoParenteses()
   * @generated
   */
  int ELEMENTO_PARENTESES = 8;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTO_PARENTESES__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTO_PARENTESES__DIREITA = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Elemento Parenteses</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTO_PARENTESES_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.ParentesesImpl <em>Parenteses</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.ParentesesImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getParenteses()
   * @generated
   */
  int PARENTESES = 9;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTESES__DIREITA = 0;

  /**
   * The number of structural features of the '<em>Parenteses</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTESES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.MatrizImpl <em>Matriz</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.MatrizImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getMatriz()
   * @generated
   */
  int MATRIZ = 10;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATRIZ__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATRIZ__VARIAVEL = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATRIZ__DIREITA = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Matriz</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATRIZ_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.PosicaoMatrizImpl <em>Posicao Matriz</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.PosicaoMatrizImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getPosicaoMatriz()
   * @generated
   */
  int POSICAO_MATRIZ = 11;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSICAO_MATRIZ__DIREITA = 0;

  /**
   * The number of structural features of the '<em>Posicao Matriz</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSICAO_MATRIZ_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.OuImpl <em>Ou</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.OuImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getOu()
   * @generated
   */
  int OU = 12;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OU__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OU__DIREITA = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ou</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OU_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.EImpl <em>E</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.EImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getE()
   * @generated
   */
  int E = 13;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int E__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int E__DIREITA = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>E</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int E_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.XouImpl <em>Xou</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.XouImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getXou()
   * @generated
   */
  int XOU = 14;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XOU__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XOU__DIREITA = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Xou</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XOU_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.ComparacaoImpl <em>Comparacao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.ComparacaoImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getComparacao()
   * @generated
   */
  int COMPARACAO = 15;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACAO__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Comparacao</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACAO__COMPARACAO = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACAO__DIREITA = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Comparacao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARACAO_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.AdicaoOuSubtracaoImpl <em>Adicao Ou Subtracao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.AdicaoOuSubtracaoImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getAdicaoOuSubtracao()
   * @generated
   */
  int ADICAO_OU_SUBTRACAO = 16;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADICAO_OU_SUBTRACAO__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Operacao</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADICAO_OU_SUBTRACAO__OPERACAO = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADICAO_OU_SUBTRACAO__DIREITA = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Adicao Ou Subtracao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADICAO_OU_SUBTRACAO_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.MultiplicacaoOuDivisaoImpl <em>Multiplicacao Ou Divisao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.MultiplicacaoOuDivisaoImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getMultiplicacaoOuDivisao()
   * @generated
   */
  int MULTIPLICACAO_OU_DIVISAO = 17;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICACAO_OU_DIVISAO__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Operacao</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICACAO_OU_DIVISAO__OPERACAO = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICACAO_OU_DIVISAO__DIREITA = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Multiplicacao Ou Divisao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICACAO_OU_DIVISAO_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.ExponenciacaoImpl <em>Exponenciacao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.ExponenciacaoImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getExponenciacao()
   * @generated
   */
  int EXPONENCIACAO = 18;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPONENCIACAO__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Direita</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPONENCIACAO__DIREITA = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Exponenciacao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPONENCIACAO_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.ConstanteInteiraImpl <em>Constante Inteira</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.ConstanteInteiraImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getConstanteInteira()
   * @generated
   */
  int CONSTANTE_INTEIRA = 19;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_INTEIRA__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_INTEIRA__VALOR = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Constante Inteira</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_INTEIRA_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.ConstanteRealImpl <em>Constante Real</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.ConstanteRealImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getConstanteReal()
   * @generated
   */
  int CONSTANTE_REAL = 20;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_REAL__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_REAL__VALOR = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Constante Real</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_REAL_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.ConstanteStringImpl <em>Constante String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.ConstanteStringImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getConstanteString()
   * @generated
   */
  int CONSTANTE_STRING = 21;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_STRING__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Valor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_STRING__VALOR = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Constante String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANTE_STRING_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.coral.portugolcoral.impl.ReferenciaVariavelImpl <em>Referencia Variavel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.coral.portugolcoral.impl.ReferenciaVariavelImpl
   * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getReferenciaVariavel()
   * @generated
   */
  int REFERENCIA_VARIAVEL = 22;

  /**
   * The feature id for the '<em><b>Esquerda</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCIA_VARIAVEL__ESQUERDA = EXPRESSAO__ESQUERDA;

  /**
   * The feature id for the '<em><b>Variavel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCIA_VARIAVEL__VARIAVEL = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Referencia Variavel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCIA_VARIAVEL_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Portugolcoral <em>Portugolcoral</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Portugolcoral</em>'.
   * @see org.xtext.coral.portugolcoral.Portugolcoral
   * @generated
   */
  EClass getPortugolcoral();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.coral.portugolcoral.Portugolcoral#getElementos <em>Elementos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elementos</em>'.
   * @see org.xtext.coral.portugolcoral.Portugolcoral#getElementos()
   * @see #getPortugolcoral()
   * @generated
   */
  EReference getPortugolcoral_Elementos();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Acoes <em>Acoes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Acoes</em>'.
   * @see org.xtext.coral.portugolcoral.Acoes
   * @generated
   */
  EClass getAcoes();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.DeclararVariaveis <em>Declarar Variaveis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declarar Variaveis</em>'.
   * @see org.xtext.coral.portugolcoral.DeclararVariaveis
   * @generated
   */
  EClass getDeclararVariaveis();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.coral.portugolcoral.DeclararVariaveis#getElementos <em>Elementos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elementos</em>'.
   * @see org.xtext.coral.portugolcoral.DeclararVariaveis#getElementos()
   * @see #getDeclararVariaveis()
   * @generated
   */
  EReference getDeclararVariaveis_Elementos();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.DeclararVariaveisTipo <em>Declarar Variaveis Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declarar Variaveis Tipo</em>'.
   * @see org.xtext.coral.portugolcoral.DeclararVariaveisTipo
   * @generated
   */
  EClass getDeclararVariaveisTipo();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.coral.portugolcoral.DeclararVariaveisTipo#getElementos <em>Elementos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Elementos</em>'.
   * @see org.xtext.coral.portugolcoral.DeclararVariaveisTipo#getElementos()
   * @see #getDeclararVariaveisTipo()
   * @generated
   */
  EAttribute getDeclararVariaveisTipo_Elementos();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coral.portugolcoral.DeclararVariaveisTipo#getTipo <em>Tipo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tipo</em>'.
   * @see org.xtext.coral.portugolcoral.DeclararVariaveisTipo#getTipo()
   * @see #getDeclararVariaveisTipo()
   * @generated
   */
  EAttribute getDeclararVariaveisTipo_Tipo();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Atribuir <em>Atribuir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Atribuir</em>'.
   * @see org.xtext.coral.portugolcoral.Atribuir
   * @generated
   */
  EClass getAtribuir();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coral.portugolcoral.Atribuir#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variavel</em>'.
   * @see org.xtext.coral.portugolcoral.Atribuir#getVariavel()
   * @see #getAtribuir()
   * @generated
   */
  EAttribute getAtribuir_Variavel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.Atribuir#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Valor</em>'.
   * @see org.xtext.coral.portugolcoral.Atribuir#getValor()
   * @see #getAtribuir()
   * @generated
   */
  EReference getAtribuir_Valor();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Expressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expressao</em>'.
   * @see org.xtext.coral.portugolcoral.Expressao
   * @generated
   */
  EClass getExpressao();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.Expressao#getEsquerda <em>Esquerda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Esquerda</em>'.
   * @see org.xtext.coral.portugolcoral.Expressao#getEsquerda()
   * @see #getExpressao()
   * @generated
   */
  EReference getExpressao_Esquerda();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Nao <em>Nao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nao</em>'.
   * @see org.xtext.coral.portugolcoral.Nao
   * @generated
   */
  EClass getNao();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.coral.portugolcoral.Nao#getNaos <em>Naos</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Naos</em>'.
   * @see org.xtext.coral.portugolcoral.Nao#getNaos()
   * @see #getNao()
   * @generated
   */
  EAttribute getNao_Naos();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.Nao#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.Nao#getDireita()
   * @see #getNao()
   * @generated
   */
  EReference getNao_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Sinal <em>Sinal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sinal</em>'.
   * @see org.xtext.coral.portugolcoral.Sinal
   * @generated
   */
  EClass getSinal();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.coral.portugolcoral.Sinal#getSinais <em>Sinais</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Sinais</em>'.
   * @see org.xtext.coral.portugolcoral.Sinal#getSinais()
   * @see #getSinal()
   * @generated
   */
  EAttribute getSinal_Sinais();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.Sinal#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.Sinal#getDireita()
   * @see #getSinal()
   * @generated
   */
  EReference getSinal_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.ElementoParenteses <em>Elemento Parenteses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Elemento Parenteses</em>'.
   * @see org.xtext.coral.portugolcoral.ElementoParenteses
   * @generated
   */
  EClass getElementoParenteses();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.ElementoParenteses#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.ElementoParenteses#getDireita()
   * @see #getElementoParenteses()
   * @generated
   */
  EReference getElementoParenteses_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Parenteses <em>Parenteses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parenteses</em>'.
   * @see org.xtext.coral.portugolcoral.Parenteses
   * @generated
   */
  EClass getParenteses();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.Parenteses#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.Parenteses#getDireita()
   * @see #getParenteses()
   * @generated
   */
  EReference getParenteses_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Matriz <em>Matriz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Matriz</em>'.
   * @see org.xtext.coral.portugolcoral.Matriz
   * @generated
   */
  EClass getMatriz();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coral.portugolcoral.Matriz#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variavel</em>'.
   * @see org.xtext.coral.portugolcoral.Matriz#getVariavel()
   * @see #getMatriz()
   * @generated
   */
  EAttribute getMatriz_Variavel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.coral.portugolcoral.Matriz#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.Matriz#getDireita()
   * @see #getMatriz()
   * @generated
   */
  EReference getMatriz_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.PosicaoMatriz <em>Posicao Matriz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Posicao Matriz</em>'.
   * @see org.xtext.coral.portugolcoral.PosicaoMatriz
   * @generated
   */
  EClass getPosicaoMatriz();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.PosicaoMatriz#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.PosicaoMatriz#getDireita()
   * @see #getPosicaoMatriz()
   * @generated
   */
  EReference getPosicaoMatriz_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Ou <em>Ou</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ou</em>'.
   * @see org.xtext.coral.portugolcoral.Ou
   * @generated
   */
  EClass getOu();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.Ou#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.Ou#getDireita()
   * @see #getOu()
   * @generated
   */
  EReference getOu_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.E <em>E</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>E</em>'.
   * @see org.xtext.coral.portugolcoral.E
   * @generated
   */
  EClass getE();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.E#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.E#getDireita()
   * @see #getE()
   * @generated
   */
  EReference getE_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Xou <em>Xou</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Xou</em>'.
   * @see org.xtext.coral.portugolcoral.Xou
   * @generated
   */
  EClass getXou();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.Xou#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.Xou#getDireita()
   * @see #getXou()
   * @generated
   */
  EReference getXou_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Comparacao <em>Comparacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparacao</em>'.
   * @see org.xtext.coral.portugolcoral.Comparacao
   * @generated
   */
  EClass getComparacao();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coral.portugolcoral.Comparacao#getComparacao <em>Comparacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparacao</em>'.
   * @see org.xtext.coral.portugolcoral.Comparacao#getComparacao()
   * @see #getComparacao()
   * @generated
   */
  EAttribute getComparacao_Comparacao();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.Comparacao#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.Comparacao#getDireita()
   * @see #getComparacao()
   * @generated
   */
  EReference getComparacao_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.AdicaoOuSubtracao <em>Adicao Ou Subtracao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Adicao Ou Subtracao</em>'.
   * @see org.xtext.coral.portugolcoral.AdicaoOuSubtracao
   * @generated
   */
  EClass getAdicaoOuSubtracao();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coral.portugolcoral.AdicaoOuSubtracao#getOperacao <em>Operacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operacao</em>'.
   * @see org.xtext.coral.portugolcoral.AdicaoOuSubtracao#getOperacao()
   * @see #getAdicaoOuSubtracao()
   * @generated
   */
  EAttribute getAdicaoOuSubtracao_Operacao();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.AdicaoOuSubtracao#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.AdicaoOuSubtracao#getDireita()
   * @see #getAdicaoOuSubtracao()
   * @generated
   */
  EReference getAdicaoOuSubtracao_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.MultiplicacaoOuDivisao <em>Multiplicacao Ou Divisao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplicacao Ou Divisao</em>'.
   * @see org.xtext.coral.portugolcoral.MultiplicacaoOuDivisao
   * @generated
   */
  EClass getMultiplicacaoOuDivisao();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coral.portugolcoral.MultiplicacaoOuDivisao#getOperacao <em>Operacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operacao</em>'.
   * @see org.xtext.coral.portugolcoral.MultiplicacaoOuDivisao#getOperacao()
   * @see #getMultiplicacaoOuDivisao()
   * @generated
   */
  EAttribute getMultiplicacaoOuDivisao_Operacao();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.MultiplicacaoOuDivisao#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.MultiplicacaoOuDivisao#getDireita()
   * @see #getMultiplicacaoOuDivisao()
   * @generated
   */
  EReference getMultiplicacaoOuDivisao_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.Exponenciacao <em>Exponenciacao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exponenciacao</em>'.
   * @see org.xtext.coral.portugolcoral.Exponenciacao
   * @generated
   */
  EClass getExponenciacao();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.coral.portugolcoral.Exponenciacao#getDireita <em>Direita</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Direita</em>'.
   * @see org.xtext.coral.portugolcoral.Exponenciacao#getDireita()
   * @see #getExponenciacao()
   * @generated
   */
  EReference getExponenciacao_Direita();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.ConstanteInteira <em>Constante Inteira</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constante Inteira</em>'.
   * @see org.xtext.coral.portugolcoral.ConstanteInteira
   * @generated
   */
  EClass getConstanteInteira();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coral.portugolcoral.ConstanteInteira#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valor</em>'.
   * @see org.xtext.coral.portugolcoral.ConstanteInteira#getValor()
   * @see #getConstanteInteira()
   * @generated
   */
  EAttribute getConstanteInteira_Valor();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.ConstanteReal <em>Constante Real</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constante Real</em>'.
   * @see org.xtext.coral.portugolcoral.ConstanteReal
   * @generated
   */
  EClass getConstanteReal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coral.portugolcoral.ConstanteReal#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valor</em>'.
   * @see org.xtext.coral.portugolcoral.ConstanteReal#getValor()
   * @see #getConstanteReal()
   * @generated
   */
  EAttribute getConstanteReal_Valor();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.ConstanteString <em>Constante String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constante String</em>'.
   * @see org.xtext.coral.portugolcoral.ConstanteString
   * @generated
   */
  EClass getConstanteString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coral.portugolcoral.ConstanteString#getValor <em>Valor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valor</em>'.
   * @see org.xtext.coral.portugolcoral.ConstanteString#getValor()
   * @see #getConstanteString()
   * @generated
   */
  EAttribute getConstanteString_Valor();

  /**
   * Returns the meta object for class '{@link org.xtext.coral.portugolcoral.ReferenciaVariavel <em>Referencia Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Referencia Variavel</em>'.
   * @see org.xtext.coral.portugolcoral.ReferenciaVariavel
   * @generated
   */
  EClass getReferenciaVariavel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.coral.portugolcoral.ReferenciaVariavel#getVariavel <em>Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variavel</em>'.
   * @see org.xtext.coral.portugolcoral.ReferenciaVariavel#getVariavel()
   * @see #getReferenciaVariavel()
   * @generated
   */
  EAttribute getReferenciaVariavel_Variavel();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PortugolcoralFactory getPortugolcoralFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.PortugolcoralImpl <em>Portugolcoral</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getPortugolcoral()
     * @generated
     */
    EClass PORTUGOLCORAL = eINSTANCE.getPortugolcoral();

    /**
     * The meta object literal for the '<em><b>Elementos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORTUGOLCORAL__ELEMENTOS = eINSTANCE.getPortugolcoral_Elementos();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.AcoesImpl <em>Acoes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.AcoesImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getAcoes()
     * @generated
     */
    EClass ACOES = eINSTANCE.getAcoes();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.DeclararVariaveisImpl <em>Declarar Variaveis</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.DeclararVariaveisImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getDeclararVariaveis()
     * @generated
     */
    EClass DECLARAR_VARIAVEIS = eINSTANCE.getDeclararVariaveis();

    /**
     * The meta object literal for the '<em><b>Elementos</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARAR_VARIAVEIS__ELEMENTOS = eINSTANCE.getDeclararVariaveis_Elementos();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.DeclararVariaveisTipoImpl <em>Declarar Variaveis Tipo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.DeclararVariaveisTipoImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getDeclararVariaveisTipo()
     * @generated
     */
    EClass DECLARAR_VARIAVEIS_TIPO = eINSTANCE.getDeclararVariaveisTipo();

    /**
     * The meta object literal for the '<em><b>Elementos</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARAR_VARIAVEIS_TIPO__ELEMENTOS = eINSTANCE.getDeclararVariaveisTipo_Elementos();

    /**
     * The meta object literal for the '<em><b>Tipo</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARAR_VARIAVEIS_TIPO__TIPO = eINSTANCE.getDeclararVariaveisTipo_Tipo();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.AtribuirImpl <em>Atribuir</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.AtribuirImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getAtribuir()
     * @generated
     */
    EClass ATRIBUIR = eINSTANCE.getAtribuir();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATRIBUIR__VARIAVEL = eINSTANCE.getAtribuir_Variavel();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATRIBUIR__VALOR = eINSTANCE.getAtribuir_Valor();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.ExpressaoImpl <em>Expressao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.ExpressaoImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getExpressao()
     * @generated
     */
    EClass EXPRESSAO = eINSTANCE.getExpressao();

    /**
     * The meta object literal for the '<em><b>Esquerda</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSAO__ESQUERDA = eINSTANCE.getExpressao_Esquerda();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.NaoImpl <em>Nao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.NaoImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getNao()
     * @generated
     */
    EClass NAO = eINSTANCE.getNao();

    /**
     * The meta object literal for the '<em><b>Naos</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAO__NAOS = eINSTANCE.getNao_Naos();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAO__DIREITA = eINSTANCE.getNao_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.SinalImpl <em>Sinal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.SinalImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getSinal()
     * @generated
     */
    EClass SINAL = eINSTANCE.getSinal();

    /**
     * The meta object literal for the '<em><b>Sinais</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINAL__SINAIS = eINSTANCE.getSinal_Sinais();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SINAL__DIREITA = eINSTANCE.getSinal_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.ElementoParentesesImpl <em>Elemento Parenteses</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.ElementoParentesesImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getElementoParenteses()
     * @generated
     */
    EClass ELEMENTO_PARENTESES = eINSTANCE.getElementoParenteses();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENTO_PARENTESES__DIREITA = eINSTANCE.getElementoParenteses_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.ParentesesImpl <em>Parenteses</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.ParentesesImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getParenteses()
     * @generated
     */
    EClass PARENTESES = eINSTANCE.getParenteses();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARENTESES__DIREITA = eINSTANCE.getParenteses_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.MatrizImpl <em>Matriz</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.MatrizImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getMatriz()
     * @generated
     */
    EClass MATRIZ = eINSTANCE.getMatriz();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATRIZ__VARIAVEL = eINSTANCE.getMatriz_Variavel();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MATRIZ__DIREITA = eINSTANCE.getMatriz_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.PosicaoMatrizImpl <em>Posicao Matriz</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.PosicaoMatrizImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getPosicaoMatriz()
     * @generated
     */
    EClass POSICAO_MATRIZ = eINSTANCE.getPosicaoMatriz();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POSICAO_MATRIZ__DIREITA = eINSTANCE.getPosicaoMatriz_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.OuImpl <em>Ou</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.OuImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getOu()
     * @generated
     */
    EClass OU = eINSTANCE.getOu();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OU__DIREITA = eINSTANCE.getOu_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.EImpl <em>E</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.EImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getE()
     * @generated
     */
    EClass E = eINSTANCE.getE();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference E__DIREITA = eINSTANCE.getE_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.XouImpl <em>Xou</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.XouImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getXou()
     * @generated
     */
    EClass XOU = eINSTANCE.getXou();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XOU__DIREITA = eINSTANCE.getXou_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.ComparacaoImpl <em>Comparacao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.ComparacaoImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getComparacao()
     * @generated
     */
    EClass COMPARACAO = eINSTANCE.getComparacao();

    /**
     * The meta object literal for the '<em><b>Comparacao</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARACAO__COMPARACAO = eINSTANCE.getComparacao_Comparacao();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARACAO__DIREITA = eINSTANCE.getComparacao_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.AdicaoOuSubtracaoImpl <em>Adicao Ou Subtracao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.AdicaoOuSubtracaoImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getAdicaoOuSubtracao()
     * @generated
     */
    EClass ADICAO_OU_SUBTRACAO = eINSTANCE.getAdicaoOuSubtracao();

    /**
     * The meta object literal for the '<em><b>Operacao</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADICAO_OU_SUBTRACAO__OPERACAO = eINSTANCE.getAdicaoOuSubtracao_Operacao();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADICAO_OU_SUBTRACAO__DIREITA = eINSTANCE.getAdicaoOuSubtracao_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.MultiplicacaoOuDivisaoImpl <em>Multiplicacao Ou Divisao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.MultiplicacaoOuDivisaoImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getMultiplicacaoOuDivisao()
     * @generated
     */
    EClass MULTIPLICACAO_OU_DIVISAO = eINSTANCE.getMultiplicacaoOuDivisao();

    /**
     * The meta object literal for the '<em><b>Operacao</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICACAO_OU_DIVISAO__OPERACAO = eINSTANCE.getMultiplicacaoOuDivisao_Operacao();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICACAO_OU_DIVISAO__DIREITA = eINSTANCE.getMultiplicacaoOuDivisao_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.ExponenciacaoImpl <em>Exponenciacao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.ExponenciacaoImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getExponenciacao()
     * @generated
     */
    EClass EXPONENCIACAO = eINSTANCE.getExponenciacao();

    /**
     * The meta object literal for the '<em><b>Direita</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPONENCIACAO__DIREITA = eINSTANCE.getExponenciacao_Direita();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.ConstanteInteiraImpl <em>Constante Inteira</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.ConstanteInteiraImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getConstanteInteira()
     * @generated
     */
    EClass CONSTANTE_INTEIRA = eINSTANCE.getConstanteInteira();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANTE_INTEIRA__VALOR = eINSTANCE.getConstanteInteira_Valor();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.ConstanteRealImpl <em>Constante Real</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.ConstanteRealImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getConstanteReal()
     * @generated
     */
    EClass CONSTANTE_REAL = eINSTANCE.getConstanteReal();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANTE_REAL__VALOR = eINSTANCE.getConstanteReal_Valor();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.ConstanteStringImpl <em>Constante String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.ConstanteStringImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getConstanteString()
     * @generated
     */
    EClass CONSTANTE_STRING = eINSTANCE.getConstanteString();

    /**
     * The meta object literal for the '<em><b>Valor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANTE_STRING__VALOR = eINSTANCE.getConstanteString_Valor();

    /**
     * The meta object literal for the '{@link org.xtext.coral.portugolcoral.impl.ReferenciaVariavelImpl <em>Referencia Variavel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.coral.portugolcoral.impl.ReferenciaVariavelImpl
     * @see org.xtext.coral.portugolcoral.impl.PortugolcoralPackageImpl#getReferenciaVariavel()
     * @generated
     */
    EClass REFERENCIA_VARIAVEL = eINSTANCE.getReferenciaVariavel();

    /**
     * The meta object literal for the '<em><b>Variavel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REFERENCIA_VARIAVEL__VARIAVEL = eINSTANCE.getReferenciaVariavel_Variavel();

  }

} //PortugolcoralPackage
