/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Referencia Variavel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.ReferenciaVariavel#getVariavel <em>Variavel</em>}</li>
 * </ul>
 *
 * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getReferenciaVariavel()
 * @model
 * @generated
 */
public interface ReferenciaVariavel extends Expressao
{
  /**
   * Returns the value of the '<em><b>Variavel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variavel</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variavel</em>' attribute.
   * @see #setVariavel(String)
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#getReferenciaVariavel_Variavel()
   * @model
   * @generated
   */
  String getVariavel();

  /**
   * Sets the value of the '{@link org.xtext.coral.portugolcoral.ReferenciaVariavel#getVariavel <em>Variavel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variavel</em>' attribute.
   * @see #getVariavel()
   * @generated
   */
  void setVariavel(String value);

} // ReferenciaVariavel
