/*
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPortugolCoralScopeProvider extends DelegatingScopeProvider {
}
