/*
 * generated by Xtext 2.16.0
 */
package org.xtext.coral


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PortugolCoralStandaloneSetup extends PortugolCoralStandaloneSetupGenerated {

	def static void doSetup() {
		new PortugolCoralStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
