/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.validation;

import org.xtext.coral.validation.AbstractPortugolCoralValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PortugolCoralValidator extends AbstractPortugolCoralValidator {
}
