/*
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.coral.services.PortugolCoralGrammarAccess;

@SuppressWarnings("all")
public class PortugolCoralSyntacticSequencer extends AbstractSyntacticSequencer {

	protected PortugolCoralGrammarAccess grammarAccess;
	protected AbstractElementAlias match_DeclararVariaveis_VariVeisKeyword_0_1_or_VariaveisKeyword_0_0;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (PortugolCoralGrammarAccess) access;
		match_DeclararVariaveis_VariVeisKeyword_0_1_or_VariaveisKeyword_0_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getDeclararVariaveisAccess().getVariVeisKeyword_0_1()), new TokenAlias(false, false, grammarAccess.getDeclararVariaveisAccess().getVariaveisKeyword_0_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_DeclararVariaveis_VariVeisKeyword_0_1_or_VariaveisKeyword_0_0.equals(syntax))
				emit_DeclararVariaveis_VariVeisKeyword_0_1_or_VariaveisKeyword_0_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'variaveis' | 'variáveis'
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '{' elementos+=DeclararVariaveisTipo
	 */
	protected void emit_DeclararVariaveis_VariVeisKeyword_0_1_or_VariaveisKeyword_0_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
