/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.coral.portugolcoral.Expressao;
import org.xtext.coral.portugolcoral.PortugolcoralPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expressao</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.impl.ExpressaoImpl#getEsquerda <em>Esquerda</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExpressaoImpl extends MinimalEObjectImpl.Container implements Expressao
{
  /**
   * The cached value of the '{@link #getEsquerda() <em>Esquerda</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEsquerda()
   * @generated
   * @ordered
   */
  protected Expressao esquerda;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpressaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PortugolcoralPackage.Literals.EXPRESSAO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expressao getEsquerda()
  {
    return esquerda;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEsquerda(Expressao newEsquerda, NotificationChain msgs)
  {
    Expressao oldEsquerda = esquerda;
    esquerda = newEsquerda;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PortugolcoralPackage.EXPRESSAO__ESQUERDA, oldEsquerda, newEsquerda);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEsquerda(Expressao newEsquerda)
  {
    if (newEsquerda != esquerda)
    {
      NotificationChain msgs = null;
      if (esquerda != null)
        msgs = ((InternalEObject)esquerda).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PortugolcoralPackage.EXPRESSAO__ESQUERDA, null, msgs);
      if (newEsquerda != null)
        msgs = ((InternalEObject)newEsquerda).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PortugolcoralPackage.EXPRESSAO__ESQUERDA, null, msgs);
      msgs = basicSetEsquerda(newEsquerda, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PortugolcoralPackage.EXPRESSAO__ESQUERDA, newEsquerda, newEsquerda));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.EXPRESSAO__ESQUERDA:
        return basicSetEsquerda(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.EXPRESSAO__ESQUERDA:
        return getEsquerda();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.EXPRESSAO__ESQUERDA:
        setEsquerda((Expressao)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.EXPRESSAO__ESQUERDA:
        setEsquerda((Expressao)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.EXPRESSAO__ESQUERDA:
        return esquerda != null;
    }
    return super.eIsSet(featureID);
  }

} //ExpressaoImpl
