/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.coral.portugolcoral.Matriz;
import org.xtext.coral.portugolcoral.PortugolcoralPackage;
import org.xtext.coral.portugolcoral.PosicaoMatriz;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Matriz</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.impl.MatrizImpl#getVariavel <em>Variavel</em>}</li>
 *   <li>{@link org.xtext.coral.portugolcoral.impl.MatrizImpl#getDireita <em>Direita</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MatrizImpl extends ExpressaoImpl implements Matriz
{
  /**
   * The default value of the '{@link #getVariavel() <em>Variavel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariavel()
   * @generated
   * @ordered
   */
  protected static final String VARIAVEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVariavel() <em>Variavel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariavel()
   * @generated
   * @ordered
   */
  protected String variavel = VARIAVEL_EDEFAULT;

  /**
   * The cached value of the '{@link #getDireita() <em>Direita</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDireita()
   * @generated
   * @ordered
   */
  protected EList<PosicaoMatriz> direita;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MatrizImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PortugolcoralPackage.Literals.MATRIZ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVariavel()
  {
    return variavel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariavel(String newVariavel)
  {
    String oldVariavel = variavel;
    variavel = newVariavel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PortugolcoralPackage.MATRIZ__VARIAVEL, oldVariavel, variavel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PosicaoMatriz> getDireita()
  {
    if (direita == null)
    {
      direita = new EObjectContainmentEList<PosicaoMatriz>(PosicaoMatriz.class, this, PortugolcoralPackage.MATRIZ__DIREITA);
    }
    return direita;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.MATRIZ__DIREITA:
        return ((InternalEList<?>)getDireita()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.MATRIZ__VARIAVEL:
        return getVariavel();
      case PortugolcoralPackage.MATRIZ__DIREITA:
        return getDireita();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.MATRIZ__VARIAVEL:
        setVariavel((String)newValue);
        return;
      case PortugolcoralPackage.MATRIZ__DIREITA:
        getDireita().clear();
        getDireita().addAll((Collection<? extends PosicaoMatriz>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.MATRIZ__VARIAVEL:
        setVariavel(VARIAVEL_EDEFAULT);
        return;
      case PortugolcoralPackage.MATRIZ__DIREITA:
        getDireita().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.MATRIZ__VARIAVEL:
        return VARIAVEL_EDEFAULT == null ? variavel != null : !VARIAVEL_EDEFAULT.equals(variavel);
      case PortugolcoralPackage.MATRIZ__DIREITA:
        return direita != null && !direita.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (variavel: ");
    result.append(variavel);
    result.append(')');
    return result.toString();
  }

} //MatrizImpl
