/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.coral.portugolcoral.MultiplicacaoOuDivisao;
import org.xtext.coral.portugolcoral.PortugolcoralPackage;
import org.xtext.coral.portugolcoral.Sinal;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Multiplicacao Ou Divisao</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.impl.MultiplicacaoOuDivisaoImpl#getOperacao <em>Operacao</em>}</li>
 *   <li>{@link org.xtext.coral.portugolcoral.impl.MultiplicacaoOuDivisaoImpl#getDireita <em>Direita</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MultiplicacaoOuDivisaoImpl extends ExpressaoImpl implements MultiplicacaoOuDivisao
{
  /**
   * The default value of the '{@link #getOperacao() <em>Operacao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperacao()
   * @generated
   * @ordered
   */
  protected static final String OPERACAO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOperacao() <em>Operacao</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperacao()
   * @generated
   * @ordered
   */
  protected String operacao = OPERACAO_EDEFAULT;

  /**
   * The cached value of the '{@link #getDireita() <em>Direita</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDireita()
   * @generated
   * @ordered
   */
  protected Sinal direita;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MultiplicacaoOuDivisaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PortugolcoralPackage.Literals.MULTIPLICACAO_OU_DIVISAO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOperacao()
  {
    return operacao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOperacao(String newOperacao)
  {
    String oldOperacao = operacao;
    operacao = newOperacao;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__OPERACAO, oldOperacao, operacao));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sinal getDireita()
  {
    return direita;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDireita(Sinal newDireita, NotificationChain msgs)
  {
    Sinal oldDireita = direita;
    direita = newDireita;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__DIREITA, oldDireita, newDireita);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDireita(Sinal newDireita)
  {
    if (newDireita != direita)
    {
      NotificationChain msgs = null;
      if (direita != null)
        msgs = ((InternalEObject)direita).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__DIREITA, null, msgs);
      if (newDireita != null)
        msgs = ((InternalEObject)newDireita).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__DIREITA, null, msgs);
      msgs = basicSetDireita(newDireita, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__DIREITA, newDireita, newDireita));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__DIREITA:
        return basicSetDireita(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__OPERACAO:
        return getOperacao();
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__DIREITA:
        return getDireita();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__OPERACAO:
        setOperacao((String)newValue);
        return;
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__DIREITA:
        setDireita((Sinal)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__OPERACAO:
        setOperacao(OPERACAO_EDEFAULT);
        return;
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__DIREITA:
        setDireita((Sinal)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__OPERACAO:
        return OPERACAO_EDEFAULT == null ? operacao != null : !OPERACAO_EDEFAULT.equals(operacao);
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO__DIREITA:
        return direita != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (operacao: ");
    result.append(operacao);
    result.append(')');
    return result.toString();
  }

} //MultiplicacaoOuDivisaoImpl
