/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.coral.portugolcoral.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PortugolcoralFactoryImpl extends EFactoryImpl implements PortugolcoralFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static PortugolcoralFactory init()
  {
    try
    {
      PortugolcoralFactory thePortugolcoralFactory = (PortugolcoralFactory)EPackage.Registry.INSTANCE.getEFactory(PortugolcoralPackage.eNS_URI);
      if (thePortugolcoralFactory != null)
      {
        return thePortugolcoralFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new PortugolcoralFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PortugolcoralFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case PortugolcoralPackage.PORTUGOLCORAL: return createPortugolcoral();
      case PortugolcoralPackage.ACOES: return createAcoes();
      case PortugolcoralPackage.DECLARAR_VARIAVEIS: return createDeclararVariaveis();
      case PortugolcoralPackage.DECLARAR_VARIAVEIS_TIPO: return createDeclararVariaveisTipo();
      case PortugolcoralPackage.ATRIBUIR: return createAtribuir();
      case PortugolcoralPackage.EXPRESSAO: return createExpressao();
      case PortugolcoralPackage.NAO: return createNao();
      case PortugolcoralPackage.SINAL: return createSinal();
      case PortugolcoralPackage.ELEMENTO_PARENTESES: return createElementoParenteses();
      case PortugolcoralPackage.PARENTESES: return createParenteses();
      case PortugolcoralPackage.MATRIZ: return createMatriz();
      case PortugolcoralPackage.POSICAO_MATRIZ: return createPosicaoMatriz();
      case PortugolcoralPackage.OU: return createOu();
      case PortugolcoralPackage.E: return createE();
      case PortugolcoralPackage.XOU: return createXou();
      case PortugolcoralPackage.COMPARACAO: return createComparacao();
      case PortugolcoralPackage.ADICAO_OU_SUBTRACAO: return createAdicaoOuSubtracao();
      case PortugolcoralPackage.MULTIPLICACAO_OU_DIVISAO: return createMultiplicacaoOuDivisao();
      case PortugolcoralPackage.EXPONENCIACAO: return createExponenciacao();
      case PortugolcoralPackage.CONSTANTE_INTEIRA: return createConstanteInteira();
      case PortugolcoralPackage.CONSTANTE_REAL: return createConstanteReal();
      case PortugolcoralPackage.CONSTANTE_STRING: return createConstanteString();
      case PortugolcoralPackage.REFERENCIA_VARIAVEL: return createReferenciaVariavel();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Portugolcoral createPortugolcoral()
  {
    PortugolcoralImpl portugolcoral = new PortugolcoralImpl();
    return portugolcoral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Acoes createAcoes()
  {
    AcoesImpl acoes = new AcoesImpl();
    return acoes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclararVariaveis createDeclararVariaveis()
  {
    DeclararVariaveisImpl declararVariaveis = new DeclararVariaveisImpl();
    return declararVariaveis;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DeclararVariaveisTipo createDeclararVariaveisTipo()
  {
    DeclararVariaveisTipoImpl declararVariaveisTipo = new DeclararVariaveisTipoImpl();
    return declararVariaveisTipo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Atribuir createAtribuir()
  {
    AtribuirImpl atribuir = new AtribuirImpl();
    return atribuir;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expressao createExpressao()
  {
    ExpressaoImpl expressao = new ExpressaoImpl();
    return expressao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nao createNao()
  {
    NaoImpl nao = new NaoImpl();
    return nao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sinal createSinal()
  {
    SinalImpl sinal = new SinalImpl();
    return sinal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ElementoParenteses createElementoParenteses()
  {
    ElementoParentesesImpl elementoParenteses = new ElementoParentesesImpl();
    return elementoParenteses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Parenteses createParenteses()
  {
    ParentesesImpl parenteses = new ParentesesImpl();
    return parenteses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Matriz createMatriz()
  {
    MatrizImpl matriz = new MatrizImpl();
    return matriz;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PosicaoMatriz createPosicaoMatriz()
  {
    PosicaoMatrizImpl posicaoMatriz = new PosicaoMatrizImpl();
    return posicaoMatriz;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ou createOu()
  {
    OuImpl ou = new OuImpl();
    return ou;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public E createE()
  {
    EImpl e = new EImpl();
    return e;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Xou createXou()
  {
    XouImpl xou = new XouImpl();
    return xou;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Comparacao createComparacao()
  {
    ComparacaoImpl comparacao = new ComparacaoImpl();
    return comparacao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AdicaoOuSubtracao createAdicaoOuSubtracao()
  {
    AdicaoOuSubtracaoImpl adicaoOuSubtracao = new AdicaoOuSubtracaoImpl();
    return adicaoOuSubtracao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MultiplicacaoOuDivisao createMultiplicacaoOuDivisao()
  {
    MultiplicacaoOuDivisaoImpl multiplicacaoOuDivisao = new MultiplicacaoOuDivisaoImpl();
    return multiplicacaoOuDivisao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Exponenciacao createExponenciacao()
  {
    ExponenciacaoImpl exponenciacao = new ExponenciacaoImpl();
    return exponenciacao;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConstanteInteira createConstanteInteira()
  {
    ConstanteInteiraImpl constanteInteira = new ConstanteInteiraImpl();
    return constanteInteira;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConstanteReal createConstanteReal()
  {
    ConstanteRealImpl constanteReal = new ConstanteRealImpl();
    return constanteReal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ConstanteString createConstanteString()
  {
    ConstanteStringImpl constanteString = new ConstanteStringImpl();
    return constanteString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReferenciaVariavel createReferenciaVariavel()
  {
    ReferenciaVariavelImpl referenciaVariavel = new ReferenciaVariavelImpl();
    return referenciaVariavel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PortugolcoralPackage getPortugolcoralPackage()
  {
    return (PortugolcoralPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static PortugolcoralPackage getPackage()
  {
    return PortugolcoralPackage.eINSTANCE;
  }

} //PortugolcoralFactoryImpl
