/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.coral.portugolcoral.Acoes;
import org.xtext.coral.portugolcoral.AdicaoOuSubtracao;
import org.xtext.coral.portugolcoral.Atribuir;
import org.xtext.coral.portugolcoral.Comparacao;
import org.xtext.coral.portugolcoral.ConstanteInteira;
import org.xtext.coral.portugolcoral.ConstanteReal;
import org.xtext.coral.portugolcoral.ConstanteString;
import org.xtext.coral.portugolcoral.DeclararVariaveis;
import org.xtext.coral.portugolcoral.DeclararVariaveisTipo;
import org.xtext.coral.portugolcoral.ElementoParenteses;
import org.xtext.coral.portugolcoral.Exponenciacao;
import org.xtext.coral.portugolcoral.Expressao;
import org.xtext.coral.portugolcoral.Matriz;
import org.xtext.coral.portugolcoral.MultiplicacaoOuDivisao;
import org.xtext.coral.portugolcoral.Nao;
import org.xtext.coral.portugolcoral.Ou;
import org.xtext.coral.portugolcoral.Parenteses;
import org.xtext.coral.portugolcoral.Portugolcoral;
import org.xtext.coral.portugolcoral.PortugolcoralFactory;
import org.xtext.coral.portugolcoral.PortugolcoralPackage;
import org.xtext.coral.portugolcoral.PosicaoMatriz;
import org.xtext.coral.portugolcoral.ReferenciaVariavel;
import org.xtext.coral.portugolcoral.Sinal;
import org.xtext.coral.portugolcoral.Xou;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PortugolcoralPackageImpl extends EPackageImpl implements PortugolcoralPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass portugolcoralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass acoesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declararVariaveisEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass declararVariaveisTipoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass atribuirEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expressaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass naoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass sinalEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass elementoParentesesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass parentesesEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass matrizEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass posicaoMatrizEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ouEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass eEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass xouEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass comparacaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass adicaoOuSubtracaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiplicacaoOuDivisaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exponenciacaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constanteInteiraEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constanteRealEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constanteStringEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass referenciaVariavelEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.coral.portugolcoral.PortugolcoralPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private PortugolcoralPackageImpl()
  {
    super(eNS_URI, PortugolcoralFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link PortugolcoralPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static PortugolcoralPackage init()
  {
    if (isInited) return (PortugolcoralPackage)EPackage.Registry.INSTANCE.getEPackage(PortugolcoralPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredPortugolcoralPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    PortugolcoralPackageImpl thePortugolcoralPackage = registeredPortugolcoralPackage instanceof PortugolcoralPackageImpl ? (PortugolcoralPackageImpl)registeredPortugolcoralPackage : new PortugolcoralPackageImpl();

    isInited = true;

    // Create package meta-data objects
    thePortugolcoralPackage.createPackageContents();

    // Initialize created meta-data
    thePortugolcoralPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    thePortugolcoralPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(PortugolcoralPackage.eNS_URI, thePortugolcoralPackage);
    return thePortugolcoralPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPortugolcoral()
  {
    return portugolcoralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPortugolcoral_Elementos()
  {
    return (EReference)portugolcoralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAcoes()
  {
    return acoesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclararVariaveis()
  {
    return declararVariaveisEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getDeclararVariaveis_Elementos()
  {
    return (EReference)declararVariaveisEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeclararVariaveisTipo()
  {
    return declararVariaveisTipoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeclararVariaveisTipo_Elementos()
  {
    return (EAttribute)declararVariaveisTipoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeclararVariaveisTipo_Tipo()
  {
    return (EAttribute)declararVariaveisTipoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAtribuir()
  {
    return atribuirEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAtribuir_Variavel()
  {
    return (EAttribute)atribuirEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAtribuir_Valor()
  {
    return (EReference)atribuirEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExpressao()
  {
    return expressaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExpressao_Esquerda()
  {
    return (EReference)expressaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNao()
  {
    return naoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNao_Naos()
  {
    return (EAttribute)naoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getNao_Direita()
  {
    return (EReference)naoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSinal()
  {
    return sinalEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSinal_Sinais()
  {
    return (EAttribute)sinalEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSinal_Direita()
  {
    return (EReference)sinalEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getElementoParenteses()
  {
    return elementoParentesesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getElementoParenteses_Direita()
  {
    return (EReference)elementoParentesesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getParenteses()
  {
    return parentesesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getParenteses_Direita()
  {
    return (EReference)parentesesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMatriz()
  {
    return matrizEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMatriz_Variavel()
  {
    return (EAttribute)matrizEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMatriz_Direita()
  {
    return (EReference)matrizEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPosicaoMatriz()
  {
    return posicaoMatrizEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPosicaoMatriz_Direita()
  {
    return (EReference)posicaoMatrizEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOu()
  {
    return ouEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOu_Direita()
  {
    return (EReference)ouEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getE()
  {
    return eEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getE_Direita()
  {
    return (EReference)eEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getXou()
  {
    return xouEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getXou_Direita()
  {
    return (EReference)xouEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComparacao()
  {
    return comparacaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComparacao_Comparacao()
  {
    return (EAttribute)comparacaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComparacao_Direita()
  {
    return (EReference)comparacaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAdicaoOuSubtracao()
  {
    return adicaoOuSubtracaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAdicaoOuSubtracao_Operacao()
  {
    return (EAttribute)adicaoOuSubtracaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAdicaoOuSubtracao_Direita()
  {
    return (EReference)adicaoOuSubtracaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMultiplicacaoOuDivisao()
  {
    return multiplicacaoOuDivisaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMultiplicacaoOuDivisao_Operacao()
  {
    return (EAttribute)multiplicacaoOuDivisaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMultiplicacaoOuDivisao_Direita()
  {
    return (EReference)multiplicacaoOuDivisaoEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExponenciacao()
  {
    return exponenciacaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExponenciacao_Direita()
  {
    return (EReference)exponenciacaoEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConstanteInteira()
  {
    return constanteInteiraEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConstanteInteira_Valor()
  {
    return (EAttribute)constanteInteiraEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConstanteReal()
  {
    return constanteRealEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConstanteReal_Valor()
  {
    return (EAttribute)constanteRealEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConstanteString()
  {
    return constanteStringEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConstanteString_Valor()
  {
    return (EAttribute)constanteStringEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getReferenciaVariavel()
  {
    return referenciaVariavelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getReferenciaVariavel_Variavel()
  {
    return (EAttribute)referenciaVariavelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PortugolcoralFactory getPortugolcoralFactory()
  {
    return (PortugolcoralFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    portugolcoralEClass = createEClass(PORTUGOLCORAL);
    createEReference(portugolcoralEClass, PORTUGOLCORAL__ELEMENTOS);

    acoesEClass = createEClass(ACOES);

    declararVariaveisEClass = createEClass(DECLARAR_VARIAVEIS);
    createEReference(declararVariaveisEClass, DECLARAR_VARIAVEIS__ELEMENTOS);

    declararVariaveisTipoEClass = createEClass(DECLARAR_VARIAVEIS_TIPO);
    createEAttribute(declararVariaveisTipoEClass, DECLARAR_VARIAVEIS_TIPO__ELEMENTOS);
    createEAttribute(declararVariaveisTipoEClass, DECLARAR_VARIAVEIS_TIPO__TIPO);

    atribuirEClass = createEClass(ATRIBUIR);
    createEAttribute(atribuirEClass, ATRIBUIR__VARIAVEL);
    createEReference(atribuirEClass, ATRIBUIR__VALOR);

    expressaoEClass = createEClass(EXPRESSAO);
    createEReference(expressaoEClass, EXPRESSAO__ESQUERDA);

    naoEClass = createEClass(NAO);
    createEAttribute(naoEClass, NAO__NAOS);
    createEReference(naoEClass, NAO__DIREITA);

    sinalEClass = createEClass(SINAL);
    createEAttribute(sinalEClass, SINAL__SINAIS);
    createEReference(sinalEClass, SINAL__DIREITA);

    elementoParentesesEClass = createEClass(ELEMENTO_PARENTESES);
    createEReference(elementoParentesesEClass, ELEMENTO_PARENTESES__DIREITA);

    parentesesEClass = createEClass(PARENTESES);
    createEReference(parentesesEClass, PARENTESES__DIREITA);

    matrizEClass = createEClass(MATRIZ);
    createEAttribute(matrizEClass, MATRIZ__VARIAVEL);
    createEReference(matrizEClass, MATRIZ__DIREITA);

    posicaoMatrizEClass = createEClass(POSICAO_MATRIZ);
    createEReference(posicaoMatrizEClass, POSICAO_MATRIZ__DIREITA);

    ouEClass = createEClass(OU);
    createEReference(ouEClass, OU__DIREITA);

    eEClass = createEClass(E);
    createEReference(eEClass, E__DIREITA);

    xouEClass = createEClass(XOU);
    createEReference(xouEClass, XOU__DIREITA);

    comparacaoEClass = createEClass(COMPARACAO);
    createEAttribute(comparacaoEClass, COMPARACAO__COMPARACAO);
    createEReference(comparacaoEClass, COMPARACAO__DIREITA);

    adicaoOuSubtracaoEClass = createEClass(ADICAO_OU_SUBTRACAO);
    createEAttribute(adicaoOuSubtracaoEClass, ADICAO_OU_SUBTRACAO__OPERACAO);
    createEReference(adicaoOuSubtracaoEClass, ADICAO_OU_SUBTRACAO__DIREITA);

    multiplicacaoOuDivisaoEClass = createEClass(MULTIPLICACAO_OU_DIVISAO);
    createEAttribute(multiplicacaoOuDivisaoEClass, MULTIPLICACAO_OU_DIVISAO__OPERACAO);
    createEReference(multiplicacaoOuDivisaoEClass, MULTIPLICACAO_OU_DIVISAO__DIREITA);

    exponenciacaoEClass = createEClass(EXPONENCIACAO);
    createEReference(exponenciacaoEClass, EXPONENCIACAO__DIREITA);

    constanteInteiraEClass = createEClass(CONSTANTE_INTEIRA);
    createEAttribute(constanteInteiraEClass, CONSTANTE_INTEIRA__VALOR);

    constanteRealEClass = createEClass(CONSTANTE_REAL);
    createEAttribute(constanteRealEClass, CONSTANTE_REAL__VALOR);

    constanteStringEClass = createEClass(CONSTANTE_STRING);
    createEAttribute(constanteStringEClass, CONSTANTE_STRING__VALOR);

    referenciaVariavelEClass = createEClass(REFERENCIA_VARIAVEL);
    createEAttribute(referenciaVariavelEClass, REFERENCIA_VARIAVEL__VARIAVEL);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    declararVariaveisEClass.getESuperTypes().add(this.getAcoes());
    atribuirEClass.getESuperTypes().add(this.getAcoes());
    naoEClass.getESuperTypes().add(this.getExpressao());
    sinalEClass.getESuperTypes().add(this.getExpressao());
    elementoParentesesEClass.getESuperTypes().add(this.getExpressao());
    matrizEClass.getESuperTypes().add(this.getExpressao());
    ouEClass.getESuperTypes().add(this.getExpressao());
    eEClass.getESuperTypes().add(this.getExpressao());
    xouEClass.getESuperTypes().add(this.getExpressao());
    comparacaoEClass.getESuperTypes().add(this.getExpressao());
    adicaoOuSubtracaoEClass.getESuperTypes().add(this.getExpressao());
    multiplicacaoOuDivisaoEClass.getESuperTypes().add(this.getExpressao());
    exponenciacaoEClass.getESuperTypes().add(this.getExpressao());
    constanteInteiraEClass.getESuperTypes().add(this.getExpressao());
    constanteRealEClass.getESuperTypes().add(this.getExpressao());
    constanteStringEClass.getESuperTypes().add(this.getExpressao());
    referenciaVariavelEClass.getESuperTypes().add(this.getExpressao());

    // Initialize classes and features; add operations and parameters
    initEClass(portugolcoralEClass, Portugolcoral.class, "Portugolcoral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPortugolcoral_Elementos(), this.getAcoes(), null, "elementos", null, 0, -1, Portugolcoral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(acoesEClass, Acoes.class, "Acoes", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(declararVariaveisEClass, DeclararVariaveis.class, "DeclararVariaveis", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getDeclararVariaveis_Elementos(), this.getDeclararVariaveisTipo(), null, "elementos", null, 0, -1, DeclararVariaveis.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(declararVariaveisTipoEClass, DeclararVariaveisTipo.class, "DeclararVariaveisTipo", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDeclararVariaveisTipo_Elementos(), ecorePackage.getEString(), "elementos", null, 0, -1, DeclararVariaveisTipo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDeclararVariaveisTipo_Tipo(), ecorePackage.getEString(), "tipo", null, 0, 1, DeclararVariaveisTipo.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(atribuirEClass, Atribuir.class, "Atribuir", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAtribuir_Variavel(), ecorePackage.getEString(), "variavel", null, 0, 1, Atribuir.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAtribuir_Valor(), this.getExpressao(), null, "valor", null, 0, 1, Atribuir.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expressaoEClass, Expressao.class, "Expressao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpressao_Esquerda(), this.getExpressao(), null, "esquerda", null, 0, 1, Expressao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(naoEClass, Nao.class, "Nao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNao_Naos(), ecorePackage.getEString(), "naos", null, 0, -1, Nao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getNao_Direita(), this.getExpressao(), null, "direita", null, 0, 1, Nao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(sinalEClass, Sinal.class, "Sinal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSinal_Sinais(), ecorePackage.getEString(), "sinais", null, 0, -1, Sinal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSinal_Direita(), this.getExpressao(), null, "direita", null, 0, 1, Sinal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(elementoParentesesEClass, ElementoParenteses.class, "ElementoParenteses", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getElementoParenteses_Direita(), this.getParenteses(), null, "direita", null, 0, 1, ElementoParenteses.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(parentesesEClass, Parenteses.class, "Parenteses", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getParenteses_Direita(), this.getExpressao(), null, "direita", null, 0, 1, Parenteses.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(matrizEClass, Matriz.class, "Matriz", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMatriz_Variavel(), ecorePackage.getEString(), "variavel", null, 0, 1, Matriz.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMatriz_Direita(), this.getPosicaoMatriz(), null, "direita", null, 0, -1, Matriz.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(posicaoMatrizEClass, PosicaoMatriz.class, "PosicaoMatriz", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPosicaoMatriz_Direita(), this.getExpressao(), null, "direita", null, 0, 1, PosicaoMatriz.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ouEClass, Ou.class, "Ou", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOu_Direita(), this.getExpressao(), null, "direita", null, 0, 1, Ou.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(eEClass, org.xtext.coral.portugolcoral.E.class, "E", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getE_Direita(), this.getExpressao(), null, "direita", null, 0, 1, org.xtext.coral.portugolcoral.E.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(xouEClass, Xou.class, "Xou", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getXou_Direita(), this.getNao(), null, "direita", null, 0, 1, Xou.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(comparacaoEClass, Comparacao.class, "Comparacao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getComparacao_Comparacao(), ecorePackage.getEString(), "comparacao", null, 0, 1, Comparacao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComparacao_Direita(), this.getExpressao(), null, "direita", null, 0, 1, Comparacao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(adicaoOuSubtracaoEClass, AdicaoOuSubtracao.class, "AdicaoOuSubtracao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAdicaoOuSubtracao_Operacao(), ecorePackage.getEString(), "operacao", null, 0, 1, AdicaoOuSubtracao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAdicaoOuSubtracao_Direita(), this.getExpressao(), null, "direita", null, 0, 1, AdicaoOuSubtracao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(multiplicacaoOuDivisaoEClass, MultiplicacaoOuDivisao.class, "MultiplicacaoOuDivisao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMultiplicacaoOuDivisao_Operacao(), ecorePackage.getEString(), "operacao", null, 0, 1, MultiplicacaoOuDivisao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMultiplicacaoOuDivisao_Direita(), this.getSinal(), null, "direita", null, 0, 1, MultiplicacaoOuDivisao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(exponenciacaoEClass, Exponenciacao.class, "Exponenciacao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExponenciacao_Direita(), this.getExpressao(), null, "direita", null, 0, 1, Exponenciacao.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constanteInteiraEClass, ConstanteInteira.class, "ConstanteInteira", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstanteInteira_Valor(), ecorePackage.getEInt(), "valor", null, 0, 1, ConstanteInteira.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constanteRealEClass, ConstanteReal.class, "ConstanteReal", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstanteReal_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, ConstanteReal.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constanteStringEClass, ConstanteString.class, "ConstanteString", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstanteString_Valor(), ecorePackage.getEString(), "valor", null, 0, 1, ConstanteString.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(referenciaVariavelEClass, ReferenciaVariavel.class, "ReferenciaVariavel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getReferenciaVariavel_Variavel(), ecorePackage.getEString(), "variavel", null, 0, 1, ReferenciaVariavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //PortugolcoralPackageImpl
