/**
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.portugolcoral.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.coral.portugolcoral.PortugolcoralPackage;
import org.xtext.coral.portugolcoral.ReferenciaVariavel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Referencia Variavel</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.coral.portugolcoral.impl.ReferenciaVariavelImpl#getVariavel <em>Variavel</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ReferenciaVariavelImpl extends ExpressaoImpl implements ReferenciaVariavel
{
  /**
   * The default value of the '{@link #getVariavel() <em>Variavel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariavel()
   * @generated
   * @ordered
   */
  protected static final String VARIAVEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVariavel() <em>Variavel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariavel()
   * @generated
   * @ordered
   */
  protected String variavel = VARIAVEL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReferenciaVariavelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PortugolcoralPackage.Literals.REFERENCIA_VARIAVEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVariavel()
  {
    return variavel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariavel(String newVariavel)
  {
    String oldVariavel = variavel;
    variavel = newVariavel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PortugolcoralPackage.REFERENCIA_VARIAVEL__VARIAVEL, oldVariavel, variavel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.REFERENCIA_VARIAVEL__VARIAVEL:
        return getVariavel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.REFERENCIA_VARIAVEL__VARIAVEL:
        setVariavel((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.REFERENCIA_VARIAVEL__VARIAVEL:
        setVariavel(VARIAVEL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PortugolcoralPackage.REFERENCIA_VARIAVEL__VARIAVEL:
        return VARIAVEL_EDEFAULT == null ? variavel != null : !VARIAVEL_EDEFAULT.equals(variavel);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (variavel: ");
    result.append(variavel);
    result.append(')');
    return result.toString();
  }

} //ReferenciaVariavelImpl
