/*
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.coral.parser.antlr.internal.InternalPortugolCoralParser;
import org.xtext.coral.services.PortugolCoralGrammarAccess;

public class PortugolCoralParser extends AbstractAntlrParser {

	@Inject
	private PortugolCoralGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPortugolCoralParser createParser(XtextTokenStream stream) {
		return new InternalPortugolCoralParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Portugolcoral";
	}

	public PortugolCoralGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PortugolCoralGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
