/*
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PortugolCoralAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/coral/parser/antlr/internal/InternalPortugolCoral.tokens");
	}
}
