/*
 * generated by Xtext 2.16.0
 */
package org.xtext.coral.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.coral.ui.internal.CoralActivator;

public class PortugolCoralUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CoralActivator.getInstance().getInjector("org.xtext.coral.PortugolCoral");
	}

}
